export const GET_QUESTIONS = "GET_QUESTIONS"
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS"
export const GET_QUESTIONS_FAIL = "GET_QUESTIONS_FAIL"

export const SEND_QUESTIONS = "SEND_QUESTIONS"
export const SEND_QUESTIONS_SUCCESS = "SEND_QUESTIONS_SUCCESS"
export const SEND_QUESTIONS_FAIL = "SEND_QUESTIONS_FAIL"